name: shadow_speak_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  audio_session: ^0.2.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  flutter_sound: ^9.2.13
  audioplayers: ^6.1.2
  record: ^5.1.2
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.4.9
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3
  custom_painter: ^1.0.0
  fl_chart: ^0.70.2
  syncfusion_flutter_sliders: ^28.2.5  
  shared_preferences: ^2.2.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  googleapis: ^13.1.0
  googleapis_auth: 
  logger: ^2.0.2
  uuid: ^4.2.2
  just_audio: ^0.10.3
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image/
    - assets/audio/
    - assets/scripts/
    - assets/subtitles/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# ← flutterと同じ階層でOK
localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-dir: lib/gen_l10n
  output-class: AppLocalizations
